name: Clean Duplicate Nodes

on:
  push:
    branches:
      - main # Trigger on push to main branch
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC
  workflow_dispatch: # Allow manual trigger from GitHub UI

jobs:
  clean-nodes:
    runs-on: ubuntu-latest # Run on latest Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch full history for accurate git diff

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use latest Python 3.x

    - name: Run node cleaning script
      run: |
        mkdir -p data # Ensure data directory exists
        python clean_duplicate_nodes.py
      # The script processes data/a.isidomain.web.id.txt and outputs to data/a.isidomain.web.id_cleaned.txt

    - name: Commit and push if changes exist
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        # Check for changes in the cleaned file
        git add data/a.isidomain.web.id_cleaned.txt

        # Commit only if there are actual content changes
        if ! git diff --cached --exit-code --quiet; then
          git commit -m "Auto: Cleaned duplicate nodes in a.isidomain.web.id_cleaned.txt"
          git push
        else
          echo "No changes in data/a.isidomain.web.id_cleaned.txt, skipping commit."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
