name: Clean Duplicate Nodes

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs daily at 00:00 UTC

jobs:
  clean-nodes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # Fetch all history for all branches and tags.
        # This is needed if the workflow needs to check for changes relative to previous commits.
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use the latest Python 3.x version

    - name: Run node cleaning script
      run: |
        python clean_nodes.py
      # The script output is automatically shown in the workflow logs.

    - name: Commit and push if changes exist
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add data/a.isidomain.web.id.txt # Ensure the specific file is added
        git diff --quiet --exit-code || git commit -m "自动: 清理重复节点" && git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
