name: Convert Nodes to YAML

on:
  schedule:
    - cron: '0 */3 * * *' # Run every 3 hours
  push:
    paths:
      - 'ss.txt'
      - 'convert.py'
  workflow_dispatch:
env:
  TZ: Asia/Shanghai
jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install geoip2 pyyaml tqdm

      - name: Run conversion script
        env:
          SOURCES: ${{ vars.SOURCES }}
        run: |
          python convert.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add config.yaml
          if ! git diff --cached --quiet; then
            # 在推送前先拉取远程最新更改
            git pull origin main --rebase
            git commit -m "Generate config.yaml from all"
            git push
          else
            echo "No changes in config.yaml, skipping commit."
          fi
