# .github/workflows/deduplicate_proxies.yml
name: Deduplicate Proxies

on:
  workflow_dispatch:
  push:
    paths:
      - 'merged_configs.txt'
      - 'all_unique_nodes.txt'
      - 'deduplicator.py'

jobs:
  deduplicate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML

      - name: Run deduplication script
        run: |
          python deduplicator.py

      - name: Upload merged config as artifact
        uses: actions/upload-artifact@v4  # 这里已更新为 v4
        with:
          name: all-proxies-yaml
          path: sc/all.yaml
