name: Nodes

# 定义触发事件
on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发
    paths:    # 只有以下路径中的文件发生变动时才触发
      - '.github/workflows/nodes.yml'
      - 'deduplication_module.py'
      - 'data/GeoLite2-Country.mmdb' # 如果此文件也提交到仓库，并且其变动也应触发
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00 运行
  workflow_dispatch:   # 支持手动触发

# 定义环境变量
env:
  PYTHON_VERSION: '3.10'  # 指定 Python 版本

jobs:
  process-nodes:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的最新 Ubuntu 运行器

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # 安装所有依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install geoip2 aiofiles httpx pyyaml beautifulsoup4

      # 创建必要的目录（如果不存在）
      - name: Create data and sub directories
        run: |
          mkdir -p data
          mkdir -p sub
          
      # 重要的 GeoLite2 数据库提醒：
      # 请确保 GeoLite2-Country.mmdb 文件已经放置在您的仓库的 'data/' 目录下，
      # 因为 GitHub Actions 运行器每次都会从头开始克隆仓库。

      # 运行节点处理和去重脚本
      - name: Run node processing and deduplication script
        run: python deduplication_module.py

      # 检查输出文件并提交更改
      - name: Commit processed nodes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # ⭐ 关键修改：首先添加并提交本地变更 ⭐
          # 这样在执行 git pull --rebase 之前，工作区是干净的。
          git add sub/deduplicated_nodes.txt
          git add sub/dns_cache.json
          
          # 检查是否有更改并提交。如果文件没有实际变化，这个 commit 不会创建新的提交。
          # 这里的提交是临时的，Rebase 后会重放到最新远程分支之上。
          git diff-index --quiet HEAD || git commit -m "WIP: Pre-pull commit from workflow"
          
          # 现在拉取最新的远程更改并进行 rebase
          # 因为之前的本地修改已经提交，所以不会再有 "unstaged changes" 的错误。
          git pull --rebase origin main
          
          # 推送到远程仓库
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
