name: Nodes

# 定义触发事件
on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00 运行
  workflow_dispatch:  # 支持手动触发

# 定义环境变量
env:
  PYTHON_VERSION: '3.10'  # 指定 Python 版本
  DATA_DIR: 'data'  # 数据目录

jobs:
  process-nodes:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的最新 Ubuntu 运行器

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install geoip2 aiofiles

      # 运行 Python 脚本
      - name: Run node processing script
        run: python deduplication_module.py

      # 检查输出文件并提交更改
      - name: Commit processed nodes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ${{ env.DATA_DIR }}/deduplicated_nodes.txt
          git diff-index --quiet HEAD || git commit -m "Update deduplicated nodes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
