name: Ultimate Proxy Node Extractor

on:
  schedule:
    - cron: '0 */6 * * *' # 每6小时运行一次 (UTC时间)
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 虚拟机

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 PyYAML # 确保安装了所有必要的库

    - name: Run Node Extraction Script
      run: |
        mkdir -p data
        python ultimate_node_extractor.py # **这里已修改为固定名称**

    - name: Commit Results # 提交更改回仓库
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        
        # 删除所有旧的代理节点切片文件，以防文件数量减少
        # 这一步非常重要，确保仓库中只保留当前次运行生成的切片
        git rm -rf data/proxy_nodes_*.txt || true # '|| true' 防止没有文件可删时报错
        
        # 添加所有新生成的切片文件、统计文件和缓存文件
        git add data/proxy_nodes_*.txt data/node_counts.csv data/url_cache.json
        
        # 检查是否有实际改动，没有改动则不提交
        git diff --cached --exit-code || git commit -m "Auto: Update proxy node list (sliced)"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
