name: Ultimate Proxy Node Extractor

on:
  schedule:
    - cron: '0 */6 * * *' # 每6小时运行一次 (UTC时间)
  workflow_dispatch: # 允许手动触发

  push: # 新增：当代码被推送到指定分支时触发
    branches:
      - main # 替换成你的主分支名称，比如 master 或 main
    paths: # 只有当这些路径下的文件发生变化时才触发
      - 'ultimate_node_extractor.py' # 你的Python脚本文件
      - 'sources.list' # 你的源列表文件
      - '.github/workflows/main.yml' # 工作流文件本身
      # 如果你的 data 目录下的文件也需要触发工作流，可以添加
      # - 'data/**' # data目录下任何文件变动都会触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 PyYAML

    - name: Run Node Extraction Script
      run: |
        mkdir -p data
        python ultimate_node_extractor.py

    - name: Commit Results
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        
        git rm -rf data/proxy_nodes_*.txt || true
        
        git add data/proxy_nodes_*.txt data/node_counts.csv data/url_cache.json
        
        git diff --cached --exit-code || git commit -m "Auto: Update proxy node list (sliced)"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
