name: Auto Update Data # 工作流名称

on:
  push: # 在每次推送到 main 分支时触发
    branches:
      - 'proxy_scraper.py'
      - '.github/workflows/proxy_scraper.yml'
  schedule: # 定时任务，每6小时运行一次
    - cron: '0 */6 * * *'
  workflow_dispatch: # 允许手动触发工作流

jobs:
  update-data:
    runs-on: ubuntu-latest # 在 Ubuntu 最新版本上运行

    steps:
      - name: Checkout repository # 步骤1: 检出仓库代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取所有历史，这对于后续的 fetch 和 hard reset 是必需的。

      - name: Configure Git # 步骤2: 配置 Git 用户信息
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Set up Python # 步骤3: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # 使用最新的 Python 3 版本，或者指定你的脚本需要的版本

      - name: Install dependencies # 步骤4: 安装 Python 依赖 (如果 proxy_scraper.py 有依赖的话)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Fetch and Hard Reset to origin/main # 步骤5: 强制同步到远程主分支
        # ⚠️ 警告: `git reset --hard` 会丢弃所有本地独有的提交，并使本地 HEAD 完全匹配远程 HEAD。
        # 只有当你确定要丢弃本地未推送的，且与远程冲突的提交时才使用此步骤。
        # 在此工作流中，由于 `stefanzweifel/git-auto-commit-action` 也带有 `pull_strategy`，
        # 此步骤可以作为额外的安全措施，或者在某些复杂情况下用于确保仓库状态干净。
        run: |
          echo "Fetching latest changes from origin..."
          git fetch origin main # 从远程获取最新的 main 分支信息

          echo "Resetting local main branch to origin/main..."
          git reset --hard origin/main
          echo "Local branch is now synced with origin/main."

      - name: Run proxy_scraper.py # 步骤6: 运行你的代理抓取脚本
        run: |
          echo "Running proxy_scraper.py..."
          python proxy_scraper.py
          echo "proxy_scraper.py finished."

      - name: Auto commit and push # 步骤7: 自动提交并推送更改
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: data/*.txt data/*.csv # 只提交 data/ 目录下的 .txt 和 .csv 文件
          commit_message: 自动更新代理节点和日志 $(date -u +'%Y-%m-%d %H:%M:%S UTC')
          commit_author: qjlxg <12179157+qjlxg@users.noreply.github.com>
          repository: .
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          pull_strategy: "pull_rebase" # 新增: 在提交前拉取并变基远程更改
          skip_dirty_check: false
          skip_fetch: false
          skip_checkout: false
          disable_globbing: false
          create_branch: false
          create_git_tag_only: false
          internal_git_binary: git
          # push_options: "--force" # 通常不需要，因为 pull_rebase 会处理好冲突
