
name: proxy_scraper

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间 00:00 运行

jobs:
  build:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 操作系统

    steps:
    - name: Checkout repository # 步骤 1: 检出代码
      uses: actions/checkout@v4

    - name: Set up Python # 步骤 2: 设置 Python 环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # 使用最新的 Python 3 版本

    - name: Install dependencies # 步骤 3: 安装所需的 Python 库
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Node Extractor Script # 步骤 4: 运行节点提取脚本
      run: |
        python proxy_scraper.py # <-- 请确保此处的脚本名称与您实际保存的脚本文件一致

    - name: Commit and Push changes # 步骤 5: 提交并推送更改
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git pull origin main --rebase || echo "No changes to pull or rebase"
        git add data/proxy_nodes_*.txt data/node_counts.csv data/url_cache.json data/failed_urls.log
        git commit -m "Update proxy nodes and logs" || echo "No changes to commit"
        git push
