name: Proxy Scraper

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

env:
  TZ: Asia/Shanghai 

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scrape_proxies:
    runs-on: ubuntu-latest
    timeout-minutes: 333

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Cache Playwright browsers
      id: cache-playwright-browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-browsers-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-playwright-browsers-

    - name: Install dependencies and Playwright browsers
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install chromium --with-deps

    - name: Run proxy scraper
      run: |
        python proxy_scraper.py
        echo "Listing contents of data/ directory after script run:"
        ls -l data/
        echo "Listing contents of cache/ directory:"
        ls -l cache/
        echo "Listing contents of root directory after script run:"
        ls -l ./

    - name: Commit and Push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

        # 检查是否有任何需要提交的更改
        if ! git diff --exit-code --quiet; then
          echo "Changes detected. Committing and pushing."
          
          # 添加所有新文件或已修改的文件
          git add data/
          git add all_unique_nodes.txt nodes_summary.csv

          # 提交更改
          git commit -m "chore: Auto-update collected proxy data [skip ci]"

          # 拉取最新更改并应用你的提交到其之上，避免合并冲突
          git pull --rebase origin main

          # 最后，推送最终结果
          git push
        else
          echo "No changes to commit. Skipping."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
