# .github/workflows/Serpapi.yml
name: Clash Proxy Crawler

on:
  schedule:
    # 每周一上午 3:00 UTC 运行
    - cron: '0 3 * * 1'
  workflow_dispatch: # 允许手动触发

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 设置 Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: |
          pip install selenium webdriver-manager pyyaml

      - name: 运行爬虫脚本
        run: |
          python clash_proxy_crawler.py

      - name: 提交更改
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "feat: 更新 Clash 代理节点和统计数据"
          file_pattern: sc/*
