name: Clash Proxy Crawler

on:
  schedule:
    # Runs every Monday at 3:00 AM UTC
    - cron: '0 3 * * 1'
  workflow_dispatch: # Allows manual trigger

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager pyyaml

      - name: Run crawler script
        run: |
          python clash_proxy_crawler.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "feat: Update Clash proxy nodes and stats"
          file_pattern: sc/*
