name: Telegram

on:
  schedule:
    - cron: '0 */6 * * *' # Run every 6 hours
  workflow_dispatch: # Allow manual triggering

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full history for rebase

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Configure Git
        run: |
          git config --global user.email "Epodonios@gmail.com"
          git config --global user.name "Epodonios"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 aiohttp pyyaml

      - name: Run V2Ray collector script
        run: |
          python Tg.py
        continue-on-error: true # Continue even if collector fails



      - name: Commit and push changes
        run: |
          git add -A
          git diff --staged --quiet || git commit -m "Update V2Ray configs, test results, and channel lists - $(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')"
          git fetch origin
          git rebase origin/main
          git push --force-with-lease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
